SELECT E.EVE_NOME, E.EVE_DATA, E.EVE_HORAINICIO, E.EVE_LOCAL, E.EVE_ENDERECO, E.EVE_CIDADE, E.EVE_ESTADO, P.PRO_DISTANCIA, P.PRO_KIT, P.PRO_VALOR, P.PRO_CATEGORIA, P.PRO_PREMIACAO  
FROM TBL_EVENTO E, TBL_PROVA P
WHERE E.ID_EVENTO = $codigo AND E.EVE_NOME = P.EVENTO;
