CREATE TABLE TBL_PROVA(
	ID_PROVA INT NOT NULL AUTO_INCREMENT,
	PRO_DISTANCIA FLOAT NOT NULL,
	PRO_KIT VARCHAR(100),
	PRO_VALOR FLOAT NOT NULL,
	PRO_CATEGORIA VARCHAR(50),
	PRO_FOTOPERCURSO BLOB,
	PRO_PREMIACAO TEXT,
	EVENTO VARCHAR(100) NOT NULL,

	CONSTRAINT PK_PROVA PRIMARY KEY (ID_PROVA),
	CONSTRAINT FK_EVENTO FOREIGN KEY (EVENTO) REFERENCES TBL_EVENTO(EVE_NOME) ON DELETE CASCADE
)