CREATE TABLE TBL_EVENTO(
	ID_EVENTO INT NOT NULL AUTO_INCREMENT,
	EVE_NOME VARCHAR(100) NOT NULL,
	EVE_DATA DATE NOT NULL,
	EVE_HORAINICIO TIME,
	EVE_IMAGEM BLOB,
	EVE_LOCAL VARCHAR(100) NOT NULL,
	EVE_ENDERECO VARCHAR(100) NOT NULL,
	EVE_NUMERO_ENDERECO SMALLINT,
	EVE_CIDADE VARCHAR(100) NOT NULL,
	EVE_ESTADO VARCHAR(2) NOT NULL,
	EVE_NPROVAS SMALLINT NOT NULL,

	CONSTRAINT PK_EVENTO PRIMARY KEY (ID_EVENTO)
);