-- TABELA USER
CREATE TABLE TBL_USER(
	ID_USER SMALLINT NOT NULL AUTO_INCREMENT,
  	USER_NOME VARCHAR(100) NOT NULL,
  	USER_CPFCNPJ VARCHAR(50) NOT NULL,
    USER_PASSWORD VARCHAR(20) NOT NULL,
    USER_EMAIL VARCHAR(50) NOT NULL,
    USER_TELEFONE VARCHAR(30),
    USER_MODERADOR CHAR(1) DEFAULT 'N',
    
    CONSTRAINT PK_USER PRIMARY KEY (ID_USER)
    
    
);

-- TABELA EVENTO
CREATE TABLE TBL_EVENTO(
	ID_EVENTO INT NOT NULL AUTO_INCREMENT,
	EVE_NOME VARCHAR(100) NOT NULL,
	EVE_DATA DATE NOT NULL,
	EVE_STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDENTE', 
	EVE_HORAINICIO TIME,
	EVE_IMAGEM BLOB,
	EVE_LOCAL VARCHAR(100) NOT NULL,
	EVE_ENDERECO VARCHAR(100) NOT NULL,
	EVE_NUMERO_ENDERECO SMALLINT,
	EVE_CIDADE VARCHAR(100) NOT NULL,
	EVE_ESTADO VARCHAR(2) NOT NULL,
	EVE_NPROVAS SMALLINT NOT NULL,
	EVE_RESULTADO VARCHAR(100) NOT NULL,
	ID_USER SMALLINT NOT NULL,

	CONSTRAINT PK_EVENTO PRIMARY KEY (ID_EVENTO),
	CONSTRAINT FK_USER FOREIGN KEY (ID_USER) REFERENCES TBL_USER(ID_USER) ON DELETE SET NULL
);

-- TABELA PROVA
CREATE TABLE TBL_PROVA(
	ID_PROVA INT NOT NULL AUTO_INCREMENT,
	PRO_DISTANCIA FLOAT NOT NULL,
	PRO_KIT VARCHAR(100),
	PRO_VALOR FLOAT NOT NULL,
	PRO_CATEGORIA VARCHAR(50),
	PRO_FOTOPERCURSO BLOB,
	PRO_PREMIACAO TEXT,
	EVENTO VARCHAR(100) NOT NULL,

	CONSTRAINT PK_PROVA PRIMARY KEY (ID_PROVA),
	CONSTRAINT FK_EVENTO FOREIGN KEY (EVENTO) REFERENCES TBL_EVENTO(EVE_NOME) ON DELETE CASCADE
);